# Stage 1: Install and build dependencies
FROM node:20 AS builder


WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .

# Stage 2: Lightweight runtime
FROM node:20-alpine AS runner


WORKDIR /app


COPY --from=builder /app .


CMD ["npx", "ts-node", "src/server.ts"]